import clsx from 'clsx'
import './globals.css'
import { Darker_Grotesque } from 'next/font/google'


const inter = Darker_Grotesque({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">


      <body className={clsx(inter.className, "bg-neutral-200 text-black")}>{children}</body>
    </html>
  )
}
